# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.25.0/namespace.json

---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
