# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.25.0/service.json

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: infra
spec:
  selector:
    app: mssql
  type: ClusterIP
  ports:
    - name: sql
      protocol: TCP
      port: 1433
      targetPort: 1433
